# Generated by Django 3.0.8 on 2020-07-23 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0002_auto_20200723_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='topic',
            field=models.CharField(choices=[('arch', 'Architecture'), ('news', 'News'), ('heal', 'Health')], max_length=4),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('aee63db4-6f17-4e5d-8e52-0a9add958932'), editable=False),
        ),
    ]
